# The config file allows you to inject Cargo.toml config into the generated crate
name = "mycrate"
version = "0.1.0-alpha"
description = "Crate description"
authors = [
  "Author1 <author1@example.com>"
  "Author2 <author2@example.com>"
]
# Some keywords are hardcoded (sdk, openapi, api, skygen), this should contain the 
# crate name and other related words.
keywords = [
  "my-crate"
]
# The api url will serve as the base for all SDK requests
api_url = "https://api.example.com/v1"

# Maintenance status of the crate
# actively-developed, passively-maintained, as-is, experimental, 
# looking-for-maintainer, deprecated
maintenance_status = "experimental"
